catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.BorrowedBooksListView.as_view(), name='borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian,
         name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/',
         views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/',
         views.AuthorDelete.as_view(), name='author_delete'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/',
         views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/',
         views.BookDelete.as_view(), name='book_delete'),

]

tuto/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

import uuid # Required for unique book instances

# Create your models here.
class Genre(models.Model):
    name=models.CharField(max_length=200, help_text= 'book genre (e.g. science fiction)')

    def __str__(self):
        return self.name


class Book(models.Model):
    title= models.CharField(max_length=200)
    author=models.ForeignKey("Author", verbose_name="authot", on_delete=models.SET_NULL, null=True)
    summary= models.TextField(max_length=1000, help_text='description of book')
    isbn=models.CharField("ISBN", max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre=models.ManyToManyField(Genre, help_text="select a genre")

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description='Genre'

    
    class Meta:
        verbose_name = "book"
        verbose_name_plural = "books"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])

class BookInstance(models.Model):
    id=models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='unique id fot this book')
    book=models.ForeignKey("Book", verbose_name="book", on_delete=models.SET_NULL, null=True)
    imprint=models.CharField( max_length=200)
    due_back=models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)    
    
    LOAD_STATUS=(
        ('m', 'Maintenance'),
        ('o', 'on loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status=models.CharField( max_length=1, choices=LOAD_STATUS, blank=True, default='m', help_text='availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)   

    def __str__(self):
        return f'{self.id} ({self.book.title})'
    @property
    def is_overdue(self):
        if self.due_back and date.today()> self.due_back:
            return True
        return False
    

class Author(models.Model):
    first_name=models.CharField( max_length=100)
    last_name=models.CharField( max_length=100)
    date_of_birth=models.DateField(null=True, blank=True)
    date_of_death=models.DateField("died",null=True, blank=True)

    
    class Meta:
        verbose_name ="Author"
        verbose_name_plural = "Authors"
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text='Enter a date between now and 4 weeks (default 3)')

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
import datetime
from django.contrib.auth.decorators import permission_required
from django.urls import reverse
from catalog.forms import RenewBookForm


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.


@login_required
def index(request):

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()

    num_authors = Author.objects.count()

    num_genres = Genre.objects.count()

    search_term = 'a'
    num_titles = Book.objects.filter(title__icontains=search_term).count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_titles': num_titles,
        'search_term': search_term,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
   # context_object_name='my_book_list'
    #queryset= Book.objects.filter(title__icontains='z')
    template_name = "book_list.html"
    paginate_by = 5

  #  def get_queryset(self):
    #     return Book.objects.filter(title__icontains='z')

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['some_data'] = 'add some info to context'
        return context


class BookDetailView(generic.DetailView):
    model = Book
    template_name = "book_detail.html"

    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            http404('Book does not exist')

        return render(request, 'catalog/book_detail.html', context={'book': book})


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5


class AuthorDetailView(generic.DetailView):
    model = Author

    def author_detail_view(request, primary_key):
        author = get_object_or_404(Author, pk=primary_key)
        return render(request, 'catalog/author_detail.html', content={'author': author})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = "bookinstance_list_borrowed_user.html"

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


class BorrowedBooksListView(PermissionRequiredMixin, generic.ListView):
    permission_required = "catalog.can_mark_returned"
    model = BookInstance
    template_name = "borrowed_books.html"

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


# @permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
        context = {
            'form': form,
            'book_instance': book_instance
        }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate (CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}


class AuthorUpdate (UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate (CreateView):
    model = Book
    fields = '__all__'


class BookUpdate (UpdateView):
    model = Book
    fields = '__all__'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% block title %}
    <title>book detail</title>
{% endblock %}


{% block content %}
<h1>{{ author.first_name}} {{ author.last_name }}</h1>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
      <hr>
    
      <a class="text-muted" href="{{  book.get_absolute_url }}">{{ book.title }}</a>
      <p>
      {{ book.summary}}
      </p>
    {% endfor %}
  </div>   

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% block title %}
    <title>author list</title>
{% endblock %}


{% block content %}
    <h1>author list</h1>

    <a href="{% url 'author_create' %}"> add author </a>   

    {% if author_list %}
        <ul>
            
        {% for author  in  author_list %}
        <li>
            <a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a> 
            <a href="{% url 'author_update' author.id %}"> update </a>   
            <a href="{% url 'author_delete' author.id %}"> delete </a>   
            
        </li>
        
        {% endfor %}

        </ul>
    {% else %}
        <p>There are no author in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete..html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the Book: {{ book.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}